# Generated by Django 4.1.7 on 2023-04-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='receiver',
            new_name='rec',
        ),
    ]
