# Generated by Django 4.1.7 on 2023-04-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_receiver_relationship_rec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='rec',
            new_name='receiver',
        ),
    ]
